php:
  container_name: php7
  build: .
  links:
    - db
  ports:
    - "8080:80"
    - "8443:443"
  volumes:
    - ./web:/var/www
  extra_hosts:
    - "docker.localhost:127.0.0.1"
db:
  container_name: db
  image: mysql:8.0
  ports:
    - "3306:3306"
  command: --default-authentication-plugin=mysql_native_password
  environment:
    MYSQL_DATABASE: agentur
    MYSQL_USER: user
    MYSQL_PASSWORD: user
    MYSQL_ROOT_PASSWORD: root
  volumes:
    - ./dump:/docker-entrypoint-initdb.d
    - ./config:/etc/mysql/conf.d
    - persistent:/var/lib/mysql
phpmyadmin:
 container_name: phpmyadmin
 image: phpmyadmin/phpmyadmin
 links:
   - db
 ports:
   - "8081:80"
